### ISSUE TITLE
[Bug] Wrong impairment_level in default config

### ISSUE THREAD

**Issue by romanziske** [TorchDSP/torchsig#319]
### Version

Other

### System Information

OS: (Linux Distro, Mac, Windows)
Environment: (Docker, venv, conda, etc)

### Description

Generating `wideband_impaired` creates the clean version instead due to an override in the default config. The required check also failed to catch this.

This bug appears on the current dev branch.

```yaml
required:
  dataset_type: wideband
  num_iq_samples_dataset: 1048576 # 1024^2
  fft_size: 1024
  num_signals_max: 5
  impairment_level: 2

overrides:
  num_samples: 57000 # 57k
  sample_rate: 100000000 # 100e6
  num_signals_min: 3
  num_signals_distribution: null
  snr_db_min: 0.0
  snr_db_max: 50.0
  signal_duration_percent_min: 0.0
  signal_duration_percent_max: 100.0
  signal_bandwidth_min:  10000 # 10e3
  signal_bandwidth_max: 100000 # 100e3
  signal_center_freq_min: -50000000 # -50e6
  signal_center_freq_max:  49999999 # 49.999999e6
  impairment_level: 0 # this value sets the impairement to clean
  class_list: all
  class_distribution: uniform
  seed: 123456789

```

### How to Reproduce the Bug

Generate the wideband impaired by the default config.
